### ISSUE TITLE
table not exists with docker-compose

### ISSUE THREAD

**Issue by changchichung** [m1k1o/blog#28]
my docker-compose.yml
```
version: "3"

services:
  webserver:
    image: m1k1o/blog:latest
    container_name: blog_apache
    environment:
      TZ: Asia/Taipei
      BLOG_DB_CONNECTION: mysql
      BLOG_MYSQL_HOST: mariadb
      BLOG_MYSQL_PORT: 3306
      BLOG_MYSQL_USER: blog
      BLOG_MYSQL_PASS: blog 
      BLOG_DB_NAME: blog
      BLOG_NICK: blog
      BLOG_PASS: blog
    restart: unless-stopped
    ports:
      - 82:80
    volumes: 
      - ./data:/var/www/html/data
  mariadb:
    image: mariadb:10.1
    container_name: blog_mariadb
    environment:
      MYSQL_USER: blog
      MYSQL_PASSWORD: blog 
      MYSQL_DATABASE: blog
      MYSQL_ROOT_PASSWORD: root 
    restart: unless-stopped
    volumes:
      - mariadb:/var/lib/mysql
      - ./app/db/mysql:/docker-entrypoint-initdb.d:ro
volumes:
  mariadb:
```
I could login , but can not post anything

error message
```
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'blog.posts' doesn't exist
```

any suggestions ?
